### ISSUE TITLE
Status of this package

### ISSUE THREAD

**Issue by aphalo** [marcpabst/ggcircular#1]
I am writing to ask about your plans for the package in this repository. I am starting to develop a package that intends to make it easier to plot circular data with 'ggplot2'. The design and functions I have in mind do not match those here, so I plan to start from scratch. I am considering what name to use for my new package. 'ggcircular' would be the obvious one, but I do not want to grab this name unless you have actually abandoned this repository and have no plans for its use. I can otherwise, make up some other name. Thanks!

**Comment by marcpabst** [comment]
Hi Pedro, thanks for opening this issue!I haven’t been working on this package for a long long time and I don’t have any intentions to do so anytime soon. So please feel free to use the name for you package.

Best, Marc

**Comment by aphalo** [comment]
Many thanks! Best wishes, Pedro.
